[tool.poetry]
name = "python-sqlalchemy"
version = "0.0.1"
description = ""
authors = ["Petr Stribny <petr@stribny.name"]

[tool.poetry.dependencies]
python = "^3.7"
sqlalchemy = "^1.3.13"
typer = "^0.0.8"
rich = "^0.3.2"
alembic = "^1.3.3"
mysql-connector = "^2.2.9"
